version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "${MONGO_DB_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE=${CUSTOMER_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      - microservices
    restart: always

  Postgresql:
    container_name: postgresql_db
    image: postgres
    restart: always
    environment:
     - POSTGRES_USER=${POSTGRESQL_DB_USERNAME}
     - POSTGRES_PASSWORD=${POSTGRESQL_DB_PASSWORD}
     - POSTGRES_DB=${PRODUCT_DB_NAME}
     - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    networks:
      - microservices
volumes:
  mongo_data:
  postgres:

networks:
  microservices:
    driver: bridge
